name: IntTest-Ubuntu

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.4

      - name: Build
        run: |
          export PATH=$PATH:$GOPATH/bin:/home/runner/go/bin:${PWD}/bin:${PWD}/bin/linux:/System/Volumes/Data/Users/runner/go/bin
          make go-bindata-download-linux tools init linux

      - name: Test in Jenkins 2.190.1
        run: |
          export PATH=$PATH:$GOPATH/bin:/home/runner/go/bin:${PWD}/bin:${PWD}/bin/linux:/System/Volumes/Data/Users/runner/go/bin
          export JENKINS_VERSION=2.190.1
          make test-slow

      - name: Test in Jenkins 2.190.2
        run: |
          export PATH=$PATH:$GOPATH/bin:/home/runner/go/bin:${PWD}/bin:${PWD}/bin/linux:/System/Volumes/Data/Users/runner/go/bin
          export JENKINS_VERSION=2.190.2
          make test-slow

      - name: Test in Jenkins 2.190.3
        run: |
          export PATH=$PATH:$GOPATH/bin:/home/runner/go/bin:${PWD}/bin:${PWD}/bin/linux:/System/Volumes/Data/Users/runner/go/bin
          export JENKINS_VERSION=2.190.2
          make test-slow

      - name: Test in Jenkins 2.204.1
        run: |
          export PATH=$PATH:$GOPATH/bin:/home/runner/go/bin:${PWD}/bin:${PWD}/bin/linux:/System/Volumes/Data/Users/runner/go/bin
          export JENKINS_VERSION=2.204.1
          make test-slow